version: '3.4'

services:
  helios-poc:
    image: ${DOCKER_REGISTRY}heliospoc
    build:
      context: .
      dockerfile: Helios-PoC/Dockerfile
    ports:
      - 80:9091/tcp
    environment:
      - HeliosIP='192.168.0.228'